"use client";

import { useState } from "react";
import { FileText, Download, Loader2 } from "lucide-react";

const MOCK_MEMO = `POLICY MEMORANDUM

TO:      Minister of Health
FROM:    Data Analytics Unit, UN Data Commons Platform
DATE:    ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
RE:      Dataset Analysis — Trust & Viability Assessment

─────────────────────────────────────────────────────────────────

EXECUTIVE SUMMARY

Based on verified UN SDG data sourced from the UN_SDG data commons, the dataset evaluated in this report has received a VIABLE designation following a rigorous three-dimensional trust assessment. The data demonstrates full metadata completeness (100%), high quality integrity (100%), and adequate freshness for policy reference purposes.

KEY FINDINGS

1. Data Integrity: All required metadata fields are present, including unit of measurement, geographic coverage, time coverage, source organisation, and license information. No missing observations were detected within the specified time range.

2. Temporal Coverage: The dataset covers the requested observation period. Analysts should note that data reflects conditions up to the last update date and may not capture developments in the intervening period.

3. Source Credibility: Data originates from a single authoritative UN SDG source (SINGLE SOURCE designation). Cross-source validation was not possible; however, UN SDG datasets are considered tier-1 authoritative for policy decision-making purposes.

POLICY IMPLICATIONS

The verified dataset is suitable for:
  • Inclusion in ministerial briefings and policy documents
  • Cross-country comparative analysis when combined with equivalent indicators for peer nations
  • Baseline setting for target-tracking against SDG commitments

The dataset should NOT be used for:
  • Real-time operational decisions requiring data from the current calendar year
  • Sub-national disaggregation without additional verification of geographic coverage

RECOMMENDED NEXT STEPS

  1. Commission a longitudinal trend analysis extending the time series to 2010 to establish long-term trajectory context.
  2. Cross-reference findings against regional averages for peer country benchmarking.
  3. Schedule a data refresh review in 12 months to reassess freshness score against updated publication timelines.

─────────────────────────────────────────────────────────────────
Generated by UN Data Commons Trust & Viability Copilot
Classification: UNCLASSIFIED · For Policy Use Only`;

export default function SynthesisEngine() {
  const [instructions, setInstructions] = useState("");
  const [status, setStatus] = useState<"idle" | "loading" | "done">("idle");

  const handleGenerate = () => {
    if (!instructions.trim()) return;
    setStatus("loading");
    setTimeout(() => setStatus("done"), 1800);
  };

  const handleDownload = () => {
    const blob = new Blob([MOCK_MEMO], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "policy_memo.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-white rounded-2xl border border-gray-200 shadow-sm p-6 space-y-5">
      {/* Header */}
      <div className="flex items-center gap-3">
        <div className="w-8 h-8 rounded-lg bg-blue-50 flex items-center justify-center flex-shrink-0">
          <FileText className="w-4 h-4 text-blue-600" strokeWidth={2} />
        </div>
        <h2 className="text-base font-bold text-gray-900">Automated Synthesis &amp; Interpretation</h2>
      </div>

      {/* Instructions input */}
      <div className="space-y-2">
        <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wider">
          Instructions for Synthesis Agent
        </label>
        <textarea
          value={instructions}
          onChange={(e) => setInstructions(e.target.value)}
          placeholder="e.g., Write a 1-page policy brief for the Minister of Health highlighting the 10% reduction in mortality..."
          rows={5}
          className="w-full px-4 py-3 border border-gray-200 rounded-xl text-sm text-gray-900 placeholder-gray-400 resize-none focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
        />
      </div>

      {/* Generate button */}
      <div className="flex justify-end">
        <button
          onClick={handleGenerate}
          disabled={!instructions.trim() || status === "loading"}
          className="flex items-center gap-2 px-6 py-2.5 bg-blue-600 hover:bg-blue-700 text-white text-sm font-semibold rounded-xl transition-colors disabled:opacity-40 disabled:cursor-not-allowed shadow-sm"
        >
          {status === "loading" && <Loader2 className="w-4 h-4 animate-spin" strokeWidth={2} />}
          {status === "loading" ? "Generating…" : "Generate Document"}
        </button>
      </div>

      {/* Generated memo */}
      {status === "done" && (
        <div className="border border-gray-200 rounded-xl overflow-hidden">
          {/* Memo toolbar */}
          <div className="flex items-center justify-between px-4 py-2.5 bg-gray-50 border-b border-gray-200">
            <span className="text-xs font-semibold text-gray-500 uppercase tracking-wider">
              Generated Policy Document
            </span>
            <button
              onClick={handleDownload}
              className="flex items-center gap-1.5 text-xs font-medium text-blue-600 hover:text-blue-800 transition-colors"
            >
              <Download className="w-3.5 h-3.5" strokeWidth={2} />
              Download PDF
            </button>
          </div>
          <pre className="p-5 text-xs text-gray-700 font-mono leading-relaxed whitespace-pre-wrap bg-white overflow-auto max-h-96">
            {MOCK_MEMO}
          </pre>
        </div>
      )}
    </div>
  );
}
